name: Brexit Document Processing
on:
  push:
    paths:
      - 'documents/**'
  workflow_dispatch:

jobs:
  process-documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytesseract pdf2image supabase pillow
          sudo apt-get update && sudo apt-get install -y tesseract-ocr poppler-utils
      - name: Process Brexit documents
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python scripts/process_brexit_docs.py
